language: python
cache: pip
python:
  - "3.6"

install: script/ci init build install bootstrap

jobs:
  allow_failures:
    - script: script/test lint
    - script: script/test docs
    - script: codecov
  include:
    - stage: "Tests"
      script:
        - script/test lint
        - script/test docs
        - script/test server
        - script/test client
        - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: cmlccie
  password:
    secure: SECURE_PASSWORD
  on:
    tags: true
    repo: CiscoDevNet/cizsle
    python: 3.6
