#!/usr/bin/env bash
# Bootstrap the project by installing all Python project dependencies.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


echo "==> Verifying project tool chains are present"


# Ensure that packages are only installed in an active virtual environment
export PIP_REQUIRE_VIRTUALENV=true


# Prefer use of a Pipfile and pipenv for dependency management
if [[ -n "$(pipenv --version 2>/dev/null)" ]]; then
    echo "==> Using pipenv to setup environment and install Pipfile dependencies"
    pipenv install --dev

elif [[ -f "requirements.txt" ]]; then

    echo "==> Checking for an active Python virtual environment"
    if [ -n "$(python -c 'import sys; print (sys.real_prefix)' 2>/dev/null)" ]; then
        echo "SUCCESS!  We are running in an active virtual environment.  We'll install the packages here."
    else
        printf "%s" \
            "VIRTUAL ENVIRONMENT ERROR: This project will only install packages into a Python virtual environment.  " \
            "Please activate the virtual environment you want to use for your work with this project and rerun the " \
            "setup script."
        exit 1
    fi

    echo "==> Installing requirements.txt dependencies"
    pip install -r requirements.txt

    echo "==> Installing requirements-dev.txt dependencies"
    pip install -r requirements-dev.txt

fi
