#!/usr/bin/env bash
# Build the project's product(s).
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


# Default build
all=true


# Process Script Arguments
for i in ${@}; do
    case ${i} in
        package)
        all=
        package=true
        ;;

        docs)
        all=
        docs=true
        ;;

        docker-dev)
        all=
        docker_dev=true
        ;;

        docker)
        all=
        docker=true
        ;;

        *)
        echo "Unknown argument: $i"
        exit 1
        ;;
    esac
done


echo "==> Cleaning previous build artifacts"
script/clean


if [[ ${all} ]] || [[ ${package} ]]; then
    echo "==> Building the Source Distribution package"
    python setup.py sdist
fi


if [[ ${all} ]] || [[ ${docs} ]]; then
    echo "==> Building the Docs"
    make -C docs clean
    make -C docs html
fi


if [[ ${all} ]] || [[ ${docker_dev} ]]; then
    echo "==> Building Development Docker Image"
    docker build -f Dockerfile.dev -t cizsle:dev ./
fi


if [[ ${all} ]] || [[ ${docker} ]]; then
    echo "==> Building Docker Image"
    docker build -f Dockerfile -t cizsle:latest ./
fi
