#!/usr/bin/env bash
# Continuous Integration and Continuous Deployment steps.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


# Default
all=true


# Process Script Arguments
for i in ${@}; do
    case ${i} in
        init)
        all=
        init=true
        ;;

        build)
        all=
        build=true
        ;;

        install)
        all=
        install=true
        ;;

        bootstrap)
        all=
        bootstrap=true
        ;;

        test)
        all=
        test=true
        ;;

        deploy)
        all=
        deploy=true
        ;;

        *)
        echo "Unknown argument: $i"
        exit 1
        ;;
    esac
done


if [[ ${all} ]] || [[ ${init} ]]; then
    echo "===> Initializing the CI environment"
    echo "Sourcing package VERSION environment variable"
    export VERSION=$(< VERSION)
fi



if [[ ${all} ]] || [[ ${build} ]]; then
    script/build package
fi


if [[ ${all} ]] || [[ ${install} ]]; then
    echo "==> Installing the Python package"
    pip install dist/cizsle-${VERSION}.tar.gz
fi


if [[ ${all} ]] || [[ ${bootstrap} ]]; then
    script/bootstrap --dev
fi



if [[ ${all} ]] || [[ ${test} ]]; then
    script/test
fi


if [[ ${deploy} ]]; then
    script/deploy
fi
