#!/usr/bin/env bash
# Run the project's test suite.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


# Initialize the CI environment
echo "==> Initializing the CI environment"


# Setup the project
script/setup --dev


# Run the test suite
script/test


# Build the product(s)
script/build


# Push the builds
