#!/usr/bin/env bash
# Build the project's product(s).
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


# Default environment
environment=dev


# Process Script Arguments
for i in ${@}; do
    case ${i} in
        dev)
        environment=dev
        ;;

        app)
        environment=app
        ;;

        *)
        echo "Unknown argument: $i"
        exit 1
        ;;
    esac
done



# Access the environment's console
case ${environment} in
    dev)
    echo "==> Connecting to the development console"
    docker run --rm -it -v "$PWD:/home/cizsle/app" cizsle:dev
    ;;

    app)
    echo "==> Connecting to the application console"
    docker run --rm -it cizsle:latest /bin/sh
    ;;
esac
