#!/usr/bin/env bash
# Setup or reset the project to its initial state.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>

set -e
cd "$(dirname "$0")/.."


echo "===> Setting up / resetting project for initial use"

script/clean --deep

script/bootstrap
