#!/usr/bin/env bash
# Run the project's test suite.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


# Default
all=true


# Process Script Arguments
for i in ${@}; do
    case ${i} in
        lint)
        all=
        lint=true
        ;;

        docs)
        all=
        docs=true
        ;;

        server)
        all=
        server=true
        ;;

        bootstrap)
        all=
        bootstrap=true
        ;;

        client)
        all=
        client=true
        ;;

        *)
        echo "Unknown argument: $i"
        exit 1
        ;;
    esac
done


if [[ ${all} ]] || [[ ${lint} ]]; then
    echo "==> Linting the source code"
    flake8
fi


if [[ ${all} ]] || [[ ${docs} ]]; then
    echo "==> Testing the cizsle docs"
    make -C docs html SPHINXOPTS="-W"
fi


if [[ ${all} ]] || [[ ${server} ]]; then
    echo "==> Running the cizsle Server test suite"
    py.test -m server
fi


if [[ ${all} ]] || [[ ${client} ]]; then
    echo "==> Running the cizsle Client test suite"
    py.test -m client
fi
