#!/usr/bin/env bash
# Update the project's dependencies.
#
# AUTHOR(s): Chris Lunsford <chrlunsf@cisco.com>


set -e
cd "$(dirname "$0")/.."


echo "===> Updating the project's dependencies"

# Ensure pipenv is installed
if ! [[ -n "$(pipenv --version 2>/dev/null)" ]]; then
    printf "%s" \
        "ERROR: Pipenv is not installed.  We are using the pipenv (https://pipenv.readthedocs.io) tool to manage the " \
        "Python dependencies for this project.  Please install pipenv and rerun this script to update the project " \
        "dependencies."
    pipenv install --dev
fi

echo "==> Updating Pipfile.lock and upgrading installed dependencies"
pipenv update

echo "==> Updating requirements.txt file"
pipenv lock -r > requirements.txt

echo "==> Updating requirements-dev.txt file"
pipenv lock -r --dev > requirements-dev.txt

echo ""
echo "SUCCESS! The project dependencies have been updated."
